"""initial schema

Revision ID: 911a9f890948
Revises:
Create Date: 2026-09-28 11:29:16.042093
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

import app.db.base
from sqlalchemy.dialects import postgresql

revision: str = "911a9f890948"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensões necessárias: e-mail case-insensitive (citext) e embeddings do RAG (pgvector).
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("logo_url", sa.String(length=512), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index(op.f("ix_companies_slug"), "companies", ["slug"], unique=True)
    op.create_table(
        "plans",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "interval",
            sa.Enum("month", "year", name="billinginterval", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("stripe_price_id", sa.String(length=128), nullable=True),
        sa.Column("asaas_plan_ref", sa.String(length=128), nullable=True),
        sa.Column("ai_requests_per_month", sa.Integer(), nullable=False),
        sa.Column("ai_tokens_per_month", sa.BigInteger(), nullable=False),
        sa.Column("max_whatsapp_connections", sa.Integer(), nullable=False),
        sa.Column("max_members", sa.Integer(), nullable=False),
        sa.Column("max_flows", sa.Integer(), nullable=False),
        sa.Column("max_knowledge_documents", sa.Integer(), nullable=False),
        sa.Column(
            "features", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("is_public", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("code", name=op.f("uq_plans_code")),
    )
    op.create_table(
        "users",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("avatar_url", sa.String(length=512), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_superuser", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "billing_events",
        sa.Column(
            "provider",
            sa.Enum("stripe", "asaas", name="billingprovider", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("external_event_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=96), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_billing_events_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_events")),
        sa.UniqueConstraint(
            "provider",
            "external_event_id",
            name=op.f("uq_billing_events_provider_external_event_id"),
        ),
    )
    op.create_index(
        op.f("ix_billing_events_company_id"), "billing_events", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_billing_events_event_type"), "billing_events", ["event_type"], unique=False
    )
    op.create_table(
        "contacts",
        sa.Column("wa_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("profile_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "tags", postgresql.ARRAY(sa.String(length=64)), server_default="{}", nullable=False
        ),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("opted_in", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_blocked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("ai_profile_summary", sa.Text(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_contacts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
        sa.UniqueConstraint("company_id", "wa_id", name=op.f("uq_contacts_company_id_wa_id")),
    )
    op.create_index(op.f("ix_contacts_company_id"), "contacts", ["company_id"], unique=False)
    op.create_table(
        "knowledge_bases",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("embedding_model", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_knowledge_bases_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_bases")),
    )
    op.create_index(
        op.f("ix_knowledge_bases_company_id"), "knowledge_bases", ["company_id"], unique=False
    )
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner", "admin", "agent", "viewer", name="memberrole", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("max_concurrent_chats", sa.Integer(), server_default="10", nullable=False),
        sa.Column("is_online", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_memberships_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint(
            "user_id", "company_id", name=op.f("uq_memberships_user_id_company_id")
        ),
    )
    op.create_index(op.f("ix_memberships_company_id"), "memberships", ["company_id"], unique=False)
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("jti", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_jti", sa.UUID(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("jti", name=op.f("uq_refresh_tokens_jti")),
    )
    op.create_index(
        "ix_refresh_tokens_user_active", "refresh_tokens", ["user_id", "revoked_at"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("stripe", "asaas", name="billingprovider", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "trialing",
                "active",
                "past_due",
                "canceled",
                "incomplete",
                "paused",
                name="subscriptionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("external_customer_id", sa.String(length=128), nullable=True),
        sa.Column("external_subscription_id", sa.String(length=128), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("grace_period_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_subscriptions_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
            name=op.f("fk_subscriptions_plan_id_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("company_id", name=op.f("uq_subscriptions_company_id")),
    )
    op.create_index(
        op.f("ix_subscriptions_company_id"), "subscriptions", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_external_customer_id"),
        "subscriptions",
        ["external_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_external_subscription_id"),
        "subscriptions",
        ["external_subscription_id"],
        unique=True,
    )
    op.create_table(
        "usage_counters",
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("ai_requests", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ai_input_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("ai_output_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("embedding_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("bonus_ai_requests", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_usage_counters_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_counters")),
        sa.UniqueConstraint(
            "company_id", "period", name=op.f("uq_usage_counters_company_id_period")
        ),
    )
    op.create_index(
        op.f("ix_usage_counters_company_id"), "usage_counters", ["company_id"], unique=False
    )
    op.create_table(
        "whatsapp_connections",
        sa.Column("phone_number_id", sa.String(length=64), nullable=False),
        sa.Column("waba_id", sa.String(length=64), nullable=False),
        sa.Column("business_id", sa.String(length=64), nullable=True),
        sa.Column("display_phone_number", sa.String(length=32), nullable=False),
        sa.Column("verified_name", sa.String(length=255), nullable=True),
        sa.Column("access_token", app.db.base.EncryptedString(), nullable=False),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "connected",
                "disconnected",
                "banned",
                "error",
                name="connectionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("quality_rating", sa.String(length=16), nullable=True),
        sa.Column("messaging_limit_tier", sa.String(length=32), nullable=True),
        sa.Column("webhook_subscribed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_whatsapp_connections_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_whatsapp_connections")),
        sa.UniqueConstraint(
            "phone_number_id", name=op.f("uq_whatsapp_connections_phone_number_id")
        ),
    )
    op.create_index(
        op.f("ix_whatsapp_connections_company_id"),
        "whatsapp_connections",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_whatsapp_connections_waba_id"), "whatsapp_connections", ["waba_id"], unique=False
    )
    op.create_table(
        "ai_agents",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "router",
                "sales",
                "support",
                "scheduling",
                "qualifier",
                "custom",
                name="agentkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("temperature", sa.Double(), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "tools", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "handoff_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("knowledge_base_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_ai_agents_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("fk_ai_agents_knowledge_base_id_knowledge_bases"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_agents")),
    )
    op.create_index(op.f("ix_ai_agents_company_id"), "ai_agents", ["company_id"], unique=False)
    op.create_table(
        "flows",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "published", "archived", name="flowstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "trigger_type",
            sa.Enum(
                "keyword",
                "default_reply",
                "welcome",
                "ad_click",
                "api",
                "manual",
                name="flowtriggertype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "trigger_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column("whatsapp_connection_id", sa.UUID(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("published_graph", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "viewport", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_flows_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["whatsapp_connection_id"],
            ["whatsapp_connections.id"],
            name=op.f("fk_flows_whatsapp_connection_id_whatsapp_connections"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flows")),
    )
    op.create_index(op.f("ix_flows_company_id"), "flows", ["company_id"], unique=False)
    op.create_index("ix_flows_company_status", "flows", ["company_id", "status"], unique=False)
    op.create_table(
        "knowledge_documents",
        sa.Column("knowledge_base_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "file",
                "url",
                "text",
                "faq",
                name="documentsourcetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_uri", sa.String(length=1024), nullable=True),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "ready",
                "failed",
                name="documentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("chunk_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_knowledge_documents_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("fk_knowledge_documents_knowledge_base_id_knowledge_bases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_documents")),
    )
    op.create_index(
        op.f("ix_knowledge_documents_company_id"),
        "knowledge_documents",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_documents_knowledge_base_id"),
        "knowledge_documents",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_base_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column(
            "meta", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_knowledge_chunks_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_documents.id"],
            name=op.f("fk_knowledge_chunks_document_id_knowledge_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_bases.id"],
            name=op.f("fk_knowledge_chunks_knowledge_base_id_knowledge_bases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
    )
    op.create_index(
        op.f("ix_knowledge_chunks_company_id"), "knowledge_chunks", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_chunks_document_id"), "knowledge_chunks", ["document_id"], unique=False
    )
    op.create_index(
        "ix_knowledge_chunks_embedding_hnsw",
        "knowledge_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_knowledge_chunks_knowledge_base_id"),
        "knowledge_chunks",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_table(
        "nodes",
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "start",
                "send_message",
                "ask_question",
                "buttons",
                "list",
                "condition",
                "ai_agent",
                "action",
                "delay",
                "handoff",
                "end",
                name="nodetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("position_x", sa.Double(), nullable=False),
        sa.Column("position_y", sa.Double(), nullable=False),
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_nodes_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"], ["flows.id"], name=op.f("fk_nodes_flow_id_flows"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
        sa.UniqueConstraint("flow_id", "client_id", name=op.f("uq_nodes_flow_id_client_id")),
    )
    op.create_index(op.f("ix_nodes_company_id"), "nodes", ["company_id"], unique=False)
    op.create_index(op.f("ix_nodes_flow_id"), "nodes", ["flow_id"], unique=False)
    op.create_table(
        "chat_sessions",
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("whatsapp_connection_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open", "pending", "closed", name="sessionstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum("flow", "ai", "human", name="sessionmode", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("assigned_user_id", sa.UUID(), nullable=True),
        sa.Column("current_flow_id", sa.UUID(), nullable=True),
        sa.Column("current_node_id", sa.UUID(), nullable=True),
        sa.Column("ai_agent_id", sa.UUID(), nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("handoff_reason", sa.String(length=255), nullable=True),
        sa.Column("ai_paused_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_inbound_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unread_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_agent_id"],
            ["ai_agents.id"],
            name=op.f("fk_chat_sessions_ai_agent_id_ai_agents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
            name=op.f("fk_chat_sessions_assigned_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_chat_sessions_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_chat_sessions_contact_id_contacts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["current_flow_id"],
            ["flows.id"],
            name=op.f("fk_chat_sessions_current_flow_id_flows"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["current_node_id"],
            ["nodes.id"],
            name=op.f("fk_chat_sessions_current_node_id_nodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["whatsapp_connection_id"],
            ["whatsapp_connections.id"],
            name=op.f("fk_chat_sessions_whatsapp_connection_id_whatsapp_connections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_sessions")),
    )
    op.create_index(
        op.f("ix_chat_sessions_assigned_user_id"),
        "chat_sessions",
        ["assigned_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_sessions_company_id"), "chat_sessions", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_sessions_contact_id"), "chat_sessions", ["contact_id"], unique=False
    )
    op.create_index(
        "ix_chat_sessions_inbox",
        "chat_sessions",
        ["company_id", "status", "last_message_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_sessions_whatsapp_connection_id"),
        "chat_sessions",
        ["whatsapp_connection_id"],
        unique=False,
    )
    op.create_index(
        "uq_chat_sessions_open_per_contact",
        "chat_sessions",
        ["contact_id", "whatsapp_connection_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'closed'"),
    )
    op.create_table(
        "edges",
        sa.Column("flow_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("source_node_id", sa.UUID(), nullable=False),
        sa.Column("target_node_id", sa.UUID(), nullable=False),
        sa.Column("source_handle", sa.String(length=64), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_edges_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"], ["flows.id"], name=op.f("fk_edges_flow_id_flows"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_node_id"],
            ["nodes.id"],
            name=op.f("fk_edges_source_node_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_node_id"],
            ["nodes.id"],
            name=op.f("fk_edges_target_node_id_nodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_edges")),
        sa.UniqueConstraint("flow_id", "client_id", name=op.f("uq_edges_flow_id_client_id")),
    )
    op.create_index(op.f("ix_edges_company_id"), "edges", ["company_id"], unique=False)
    op.create_index(op.f("ix_edges_flow_id"), "edges", ["flow_id"], unique=False)
    op.create_index(op.f("ix_edges_source_node_id"), "edges", ["source_node_id"], unique=False)
    op.create_index(op.f("ix_edges_target_node_id"), "edges", ["target_node_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("inbound", "outbound", name="messagedirection", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "sender_type",
            sa.Enum(
                "contact",
                "flow",
                "ai",
                "agent",
                "system",
                name="sendertype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("sender_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "text",
                "image",
                "audio",
                "video",
                "document",
                "sticker",
                "location",
                "contacts",
                "interactive",
                "template",
                "reaction",
                "unsupported",
                name="messagetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column(
            "content", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("wa_message_id", sa.String(length=128), nullable=True),
        sa.Column("reply_to_wa_message_id", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "queued",
                "sent",
                "delivered",
                "read",
                "failed",
                name="messagestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ai_input_tokens", sa.Integer(), nullable=True),
        sa.Column("ai_output_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_messages_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["users.id"],
            name=op.f("fk_messages_sender_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
            name=op.f("fk_messages_session_id_chat_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("wa_message_id", name=op.f("uq_messages_wa_message_id")),
    )
    op.create_index(op.f("ix_messages_company_id"), "messages", ["company_id"], unique=False)
    op.create_index(op.f("ix_messages_created_at"), "messages", ["created_at"], unique=False)
    op.create_index(
        "ix_messages_session_created", "messages", ["session_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_session_created", table_name="messages")
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages")
    op.drop_index(op.f("ix_messages_company_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_edges_target_node_id"), table_name="edges")
    op.drop_index(op.f("ix_edges_source_node_id"), table_name="edges")
    op.drop_index(op.f("ix_edges_flow_id"), table_name="edges")
    op.drop_index(op.f("ix_edges_company_id"), table_name="edges")
    op.drop_table("edges")
    op.drop_index(
        "uq_chat_sessions_open_per_contact",
        table_name="chat_sessions",
        postgresql_where=sa.text("status <> 'closed'"),
    )
    op.drop_index(op.f("ix_chat_sessions_whatsapp_connection_id"), table_name="chat_sessions")
    op.drop_index("ix_chat_sessions_inbox", table_name="chat_sessions")
    op.drop_index(op.f("ix_chat_sessions_contact_id"), table_name="chat_sessions")
    op.drop_index(op.f("ix_chat_sessions_company_id"), table_name="chat_sessions")
    op.drop_index(op.f("ix_chat_sessions_assigned_user_id"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index(op.f("ix_nodes_flow_id"), table_name="nodes")
    op.drop_index(op.f("ix_nodes_company_id"), table_name="nodes")
    op.drop_table("nodes")
    op.drop_index(op.f("ix_knowledge_chunks_knowledge_base_id"), table_name="knowledge_chunks")
    op.drop_index(
        "ix_knowledge_chunks_embedding_hnsw",
        table_name="knowledge_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_knowledge_chunks_document_id"), table_name="knowledge_chunks")
    op.drop_index(op.f("ix_knowledge_chunks_company_id"), table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    op.drop_index(
        op.f("ix_knowledge_documents_knowledge_base_id"), table_name="knowledge_documents"
    )
    op.drop_index(op.f("ix_knowledge_documents_company_id"), table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    op.drop_index("ix_flows_company_status", table_name="flows")
    op.drop_index(op.f("ix_flows_company_id"), table_name="flows")
    op.drop_table("flows")
    op.drop_index(op.f("ix_ai_agents_company_id"), table_name="ai_agents")
    op.drop_table("ai_agents")
    op.drop_index(op.f("ix_whatsapp_connections_waba_id"), table_name="whatsapp_connections")
    op.drop_index(op.f("ix_whatsapp_connections_company_id"), table_name="whatsapp_connections")
    op.drop_table("whatsapp_connections")
    op.drop_index(op.f("ix_usage_counters_company_id"), table_name="usage_counters")
    op.drop_table("usage_counters")
    op.drop_index(op.f("ix_subscriptions_external_subscription_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_external_customer_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_company_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index("ix_refresh_tokens_user_active", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_company_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_knowledge_bases_company_id"), table_name="knowledge_bases")
    op.drop_table("knowledge_bases")
    op.drop_index(op.f("ix_contacts_company_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_billing_events_event_type"), table_name="billing_events")
    op.drop_index(op.f("ix_billing_events_company_id"), table_name="billing_events")
    op.drop_table("billing_events")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("plans")
    op.drop_index(op.f("ix_companies_slug"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
